# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build ISOs 

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    

jobs:
  container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Build Docker container 
        run: |
          docker build --rm --network=host -t ash-os:latest .
          # docker run --rm -it --privileged -v $HOME/docker/volumes/ash-os:/build/out ash-os:latest
          # docker run -d --privileged -v $(pwd)/out:/build/out ash-os:latest
      - name: Run Docker container 
        run: | 
          docker run -v $(pwd)/out:/build/out --privileged ash-os:latest
      - name: Create ISO release 
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: out/*.iso
